// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';
import redirects from './src/redirects.mjs';

// URL structure preserved 1:1 with the WordPress site (trailing-slash directories)
// so every backlink and indexed URL keeps working — no SEO equity lost.
// `redirects` maps legacy in-content URLs to their current page (generated by
// scripts/generate_redirects.py) so no internal link 404s.
// The Vercel adapter exists solely for the /api/lead endpoint (form
// submissions -> Vercel Blob); every page remains statically prerendered.
export default defineConfig({
  site: 'https://www.ayurvedicwellnesscentre.com.au',
  trailingSlash: 'always',
  build: { format: 'directory' },
  redirects,
  integrations: [sitemap()],
  adapter: vercel(),
});
